apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 31757
      websecure:
        exposed: false
    nodeSelector:
      mode: relay
    logs:
      access:
        enabled: true
