---
services:
  snake:
    image: conesnake:latest-dev
    build:
      target: dev
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      - RUST_BACKTRACE
      - TARGET
      - NUM_THREADS
      - NUM_WORKERS
      - MAX_BOARDS
      - MAX_WIDTH
      - MAX_HEIGHT
      - MAX_SNAKES
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"
    cap_add:
      - CAP_PERFMON
    command: |
      scripts/entrypoint_relay.sh \
        --max-boards 0 \
        --max-width ${MAX_WIDTH:-11} \
        --max-height ${MAX_HEIGHT:-11} \
        --max-snakes ${MAX_SNAKES:-4} \
        --num-parallel-reqs 1 \
        --worker-node worker \
        --worker-pod http://worker-0:8081 \
        --worker-pod http://worker-1:8081 \
        --worker-pod http://worker-2:8081 \
        relay

  worker-0: &worker
    image: conesnake:latest-dev
    environment:
      - RUST_BACKTRACE
      - TARGET
    volumes:
      - ".:/app"
    cap_add:
      - CAP_PERFMON
    command: |
      scripts/entrypoint.sh \
        --port 8081 \
        --num-worker-threads ${NUM_THREADS:-4} \
        --max-boards ${MAX_BOARDS:-10000} \
        --max-width ${MAX_WIDTH:-11} \
        --max-height ${MAX_HEIGHT:-11} \
        --max-snakes ${MAX_SNAKES:-4} \
        worker

  worker-1:
    <<: *worker

  worker-2:
    <<: *worker

  snork-flood: &snork
    build:
      context: submodules/snork
      args:
        UID: ${UID}
        GID: ${GID}
    deploy:
      resources:
        limits:
          cpus: "2"
    ports:
      - "8082:8082"
    command: ["--host", "0.0.0.0:8082", "--color", "#4400ff", "--config", "{ \"Flood\": {} }"]

  snork-tree:
    <<: *snork
    ports:
      - "8083:8083"
    command: ["--host", "0.0.0.0:8083", "--color", "#00ff59", "--config", "{ \"Tree\": {} }"]

  snork-mobility:
    <<: *snork
    ports:
      - "8084:8084"
    command: ["--host", "0.0.0.0:8084", "--color", "#ffff00", "--config", "{ \"Mobility\": {} }"]

  rules:
    image: conesnake:latest-dev
    network_mode: host
    volumes:
      - ".:/app"
    command: |
      scripts/entrypoint_rules.sh \
        --browser \
        --board-url http://localhost:5173 \
        --timeout 500 \
        --width 11 --height 11 \
        --gametype standard \
        --map standard \
        --foodSpawnChance 15 \
        --hazardDamagePerTurn 16 \
        --name conesnake --url http://localhost:${LISTEN_PORT:-8080} \
        --name snork-flood --url http://localhost:8082 \
        --name snork-tree --url http://localhost:8083 \
        --name snork-mobility --url http://localhost:8084 \

  board:
    build:
      context: submodules/board
    ports:
      - "5173:5173"
    command: |
      npm run dev
