services:
  snake:
    image: snake_dev:latest
    build:
      target: dev
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      - RUST_BACKTRACE
      - TARGET
    volumes:
      - .:/app
    command: |
      ./entrypoint.sh --max-boards 400000 \
      --max-width 11 --max-height 11

  player:
    build:
      context: gpu
      target: dev
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/app

  rules:
    image: snake_dev:latest
    ports:
      - 4000:4000
    command: |
      entrypoint_rules.sh \
        --board \
        --board-address :4000 \
        --timeout 200 \
        --width 11 --height 11 \
        --gametype standard \
        --map standard \
        --foodSpawnChance 10 \
        --hazardDamagePerTurn 100 \
        --name treesnake --url http://snake:8080 \
        --name snork --url http://snork:8082 \
        --name snork_2 --url http://snork_2:8083 \
    depends_on:
      - snake
      - snork
      - snork_2

  board:
    build:
      context: submodules/board
      target: build
    ports:
      - 127.0.0.1:3000:3000
    command: [ "npm", "run", "start" ]

  snork:
    build:
      context: submodules/snork
      args:
        UID: ${UID}
        GID: ${GID}
    command: |
      cargo run --release -- --host 0.0.0.0:8082

  snork_2:
    build:
      context: submodules/snork
      args:
        UID: ${UID}
        GID: ${GID}
    command: |
      cargo run --release -- --host 0.0.0.0:8083
