version: 2.1

jobs:
  test:
    machine:
      image: "ubuntu-2204:2023.10.1"
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run:
          name: submodules
          command: git submodule update --init --recursive
      - run:
          name: environment
          command: |
            echo "UID=$(id -u)" >> .env
            echo "GID=$(id -g)" >> .env
            echo "RUST_BACKTRACE=1" >> .env
      - run:
          name: docker build
          command: docker compose build snake
      - restore_cache:
          name: restore cache
          keys:
            - cache-{{ checksum "Cargo.lock" }}
            - cache-
      - run:
          name: compile
          command: docker compose run --rm snake cargo build --tests
      - run:
          name: lint
          command: make lint
      - save_cache:
          name: save cache
          key: cache-{{ checksum "Cargo.lock" }}
          paths:
            - ./target-snake
            - ./.cargo
      - run:
          name: test
          command: make test

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
