apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  chart: aws-load-balancer-controller
  repo: https://aws.github.io/eks-charts
  version: 1.6.2
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    clusterName: "conesnake"
    defaultTags:
      deployment: "conesnake"
    image:
      repository: public.ecr.aws/eks/aws-load-balancer-controller
      tag: v2.6.2
      pullPolicy: IfNotPresent
    nodeSelector:
      mode: relay
    tolerations:
    - key: "AppPodsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
    webhookBindPort: 59205
