---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-saccount-creds"
  labels:
    {{- include "common_labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-role-secrets-rw"
  labels:
    {{- include "common_labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-creds-role-binding"
  labels:
    {{- include "common_labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-saccount-creds"
  apiGroup: ""
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-role-secrets-rw"
  apiGroup: ""
