{{- define "conesnake_common" -}}
imagePullPolicy: Always
envFrom:
- secretRef:
    name: "{{ .Release.Name }}-conesnake-secrets"
env:
- name: RUST_BACKTRACE
  value: "1"
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
ports:
- containerPort: 8080
  name: listen-port
startupProbe:
  httpGet:
    path: /
    port: listen-port
  failureThreshold: 15
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /ping
    port: listen-port
  failureThreshold: 2
  periodSeconds: 9
livenessProbe:
  httpGet:
    path: /
    port: listen-port
  failureThreshold: 1
  periodSeconds: 5
{{- end -}}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-relay"
  labels:
    {{- include "common_labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common_labels" . | nindent 6 }}
      app: relay
  replicas: {{ .Values.relay.parallel_reqs }}
  serviceName: "{{ .Release.Name }}-relay"
  podManagementPolicy: "Parallel"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "common_labels" . | nindent 8 }}
        app: relay
    spec:
      serviceAccountName: "{{ .Release.Name }}-sa-get-pods"
      nodeSelector:
        mode: relay
      tolerations:
      - key: AppPodsOnly
        operator: Equal
        value: "true"
        effect: NoExecute
      imagePullSecrets:
      - name: regcred
      terminationGracePeriodSeconds: 10
      containers:
      - name: "{{ .Release.Name }}-relay"
        {{- include "conesnake_common" . | nindent 8 }}
        image: {{ include "amd64_image" . }}
        resources:
          requests:
            memory: {{ .Values.relay.mem }}
        args:
        - "--port=8080"
        - "--max-width={{ .Values.max_width }}"
        - "--max-height={{ .Values.max_height }}"
        - "--max-snakes={{ .Values.max_snakes }}"
        - "--max-boards=0"
        - "--num-parallel-reqs={{ .Values.relay.parallel_reqs }}"
        - "--latency={{ .Values.relay.latency }}"
        {{- range $i, $worker := .Values.workers }}
        - "--worker-node=10.43.{{ add 100 $i }}"
        {{- range $j := until ($worker.replicas | int) }}
        - "--worker-pod=http://10.43.{{ add 100 $i }}.{{ $j }}:8080"
        {{- end }}
        {{- end }}
        - "relay"

{{ range $worker := .Values.workers }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $.Release.Name }}-worker-{{ $worker.hostname }}"
  labels:
    {{- include "common_labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common_labels" $ | nindent 6 }}
      app: worker
      node: "worker-{{ $worker.hostname }}"
  replicas: {{ $worker.replicas }}
  serviceName: "{{ $.Release.Name }}-worker-{{ $worker.hostname }}"
  podManagementPolicy: "Parallel"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "common_labels" $ | nindent 8 }}
        app: worker
        node: "worker-{{ $worker.hostname }}"
    spec:
      serviceAccountName: "{{ $.Release.Name }}-sa-get-pods"
      nodeName: "{{ $worker.hostname }}"
      tolerations:
      - key: AppPodsOnly
        operator: Equal
        value: "true"
        effect: NoExecute
      imagePullSecrets:
      - name: regcred
      terminationGracePeriodSeconds: 10
      containers:
      - name: "{{ $.Release.Name }}-worker"
        {{- include "conesnake_common" $ | nindent 8 }}
        image: {{ include "amd64_image" $ }}
        resources:
          requests:
            memory: {{ $.Values.worker.mem }}
        args:
        - "--port=8080"
        - "--max-width={{ $.Values.max_width }}"
        - "--max-height={{ $.Values.max_height }}"
        - "--max-snakes={{ $.Values.max_snakes }}"
        - "--max-boards={{ $.Values.worker.boards }}"
        - "--latency={{ $.Values.worker.latency }}"
        - "--num-threads={{ $.Values.worker.num_threads }}"
        - "worker"
{{ end }}
