apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}-ip-change"
  labels:
    {{- include "common_labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common_labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common_labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: "{{ .Release.Name }}-ip-change"
        image: "{{ .Values.aws_account_id }}.dkr.ecr.{{ .Values.aws_default_region }}.amazonaws.com/conesnake:latest-job"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-conesnake-secrets"
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        command:
          - /app/ip_change.sh
