---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-conesnake-secrets"
  labels:
    {{- include "common_labels" . | nindent 4 }}
stringData:
  AWS_ACCOUNT_ID: {{ .Values.aws_account_id | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws_access_key_id | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_secret_access_key | quote }}
  AWS_DEFAULT_REGION: "us-west-2"
