---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-relays"
  labels:
    {{- include "common_labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    {{- include "common_labels" . | nindent 4 }}
    app: relay

{{- range $worker := .Values.workers }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-worker-{{ $worker.hostname }}"
  labels:
    {{- include "common_labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: "{{ $worker.service_ip }}"
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "common_labels" $ | nindent 4 }}
    node: "worker-{{ $worker.hostname }}"
{{- end }}
